# Generated by Django 2.2.4 on 2019-08-05 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2d021451-5e55-496c-aa68-d0ba4f48c1e0'), primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1755ef07-71d8-4713-b45a-8ff0fd90c487'), primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb8adf46-e522-459b-94ab-8f4dbf3c5c1c'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2f66c921-1e1b-4fa2-bb19-fb2535de97bd'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(to='main.Comment')),
                ('likes', models.ManyToManyField(to='main.Like')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
