# Generated by Django 2.2.4 on 2019-08-05 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190805_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebffd6ea-592f-4ae8-a1f3-8ee33a39facd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ebfbf00-6b6a-40d3-8ed4-3c0f9a72bb58'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f312c3f3-e28a-4a45-b131-4bb1d3dd92be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f722c0de-3e2f-4527-ace9-31f73da7fddc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
